version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    commit-message:
      prefix: 'fix'
  - package-ecosystem: nuget
    directory: '/src'
    schedule:
      interval: daily
    commit-message:
      prefix: 'fix'
  - package-ecosystem: nuget
    directory: '/test'
    schedule:
      interval: daily
    commit-message:
      prefix: 'fix'