# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  push:
    branches:
      - 'main'       # Run the workflow when pushing to the main branch
  pull_request:
    branches:
      - '*'          # Run the workflow for all pull requests

concurrency:
  group: ci-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true

defaults:
  run:
    shell: pwsh

jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '2.1.x'

      - name: Run tests
        run: dotnet test --configuration Release
